apiVersion: apps/v1
kind: Deployment
metadata:
  name: stridekicks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stridekicks
  template:
    metadata:
      labels:
        app: stridekicks
    spec:
      containers:
      - name: stridekicks
        image: sanjayk221b/stridekicks
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: stridekicks-service
spec:
  type: NodePort
  selector:
    app: stridekicks
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300